apiVersion: v1
kind: ServiceAccount

metadata: 
  name: webui-admin

---

apiVersion: rbac.authorication.k8s.io/v1beta1
kind: ClusterRoleBinding

roleRef:
  apiGroup: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  name: cluster-admin

subjects:
- apiGroup: rbac.authorization.k8s.io/v1beta1
  kind: ServiceAccount
  name: webui-admin
